### ISSUE TITLE
Setup repository

### ISSUE THREAD

**Issue by agdula** [DiffKit/DiffKit#2]
I can easily setup a bintray repository but i guess we should target for the maven central

**Comment by paulsaurels** [comment]
Hi Agdula, 

The dependency problem is that:

In the  Central Maven Repository (https://repo1.maven.org/maven2)  is missim this artefact:  "cn.guoyukun.jdbc:db2jcc:jar:1.4.2" , related to these "pom" dependencies configurations:

```
    <dependency>
        <groupId>cn.guoyukun.jdbc</groupId>
        <artifactId>db2jcc</artifactId>
        <version>1.4.2</version>
    </dependency>

    <dependency>
        <groupId>cn.guoyukun.jdbc</groupId>
        <artifactId>db2jcc_license_cu</artifactId>
        <version>1.4.2</version>
    </dependency>
```

What central maven are you using in your settings.xml (other than "https://repo1.maven.org/maven2") ?

Cheers
Paulo

PS: 
My Maven Has Said:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.023s
[INFO] Finished at: Tue Nov 10 16:27:53 BRST 2015
[INFO] Final Memory: 7M/17M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project diffkit: Could not resolve dependencies for project org.diffkit:diffkit:jar:0.9.1-SNAPSHOT: The following artifacts could not be resolved: cn.guoyukun.jdbc:db2jcc:jar:1.4.2, cn.guoyukun.jdbc:db2jcc_license_cu:jar:1.4.2: Could not find artifact cn.guoyukun.jdbc:db2jcc:jar:1.4.2 in central (https://repo1.maven.org/maven2) -> [Help 1]

**Comment by agdula** [comment]
I really can't remember how i got these files in my maven repo.
I guess i must have used this http://repo.spring.io/list/plugins-release/
repo in some other project. Now i'm thinking whether we should
1. go use that repo explicitly pom file
2. add files to /repo ( possible license issues like with oracle :-)
3. just get rid of the dependency ?? or

I would vote for option three .. any suggestions ?

2015-11-10 19:50 GMT+01:00 Paulo Aurélio Da Silva notifications@github.com
:

> Hi Agdula,
> 
> The dependency problem is that:
> 
> In the Central Maven Repository (https://repo1.maven.org/maven2) is
> missim this artefact: "cn.guoyukun.jdbc:db2jcc:jar:1.4.2" , related to
> these "pom" dependencies configurations:
> 
> ```
> <dependency>
>     <groupId>cn.guoyukun.jdbc</groupId>
>     <artifactId>db2jcc</artifactId>
>     <version>1.4.2</version>
> </dependency>
> 
> <dependency>
>     <groupId>cn.guoyukun.jdbc</groupId>
>     <artifactId>db2jcc_license_cu</artifactId>
>     <version>1.4.2</version>
> </dependency>
> ```
> 
> What central maven are you using in your settings.xml (other than "
> https://repo1.maven.org/maven2") ?
> 
> Cheers
> Paulo
> 
> PS:
> My Maven Has Said:
> 
> ## [INFO]
> 
> [INFO] BUILD FAILURE
> 
> ## [INFO]
> 
> [INFO] Total time: 6.023s
> [INFO] Finished at: Tue Nov 10 16:27:53 BRST 2015
> [INFO] Final Memory: 7M/17M
> 
> ## [INFO]
> 
> [ERROR] Failed to execute goal on project diffkit: Could not resolve
> dependencies for project org.diffkit:diffkit:jar:0.9.1-SNAPSHOT: The
> following artifacts could not be resolved:
> cn.guoyukun.jdbc:db2jcc:jar:1.4.2,
> cn.guoyukun.jdbc:db2jcc_license_cu:jar:1.4.2: Could not find artifact
> cn.guoyukun.jdbc:db2jcc:jar:1.4.2 in central (
> https://repo1.maven.org/maven2) -> [Help 1]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DiffKit/DiffKit/issues/2#issuecomment-155528956.

## 

Pozdrawiam,
Andrzej

**Comment by paulsaurels** [comment]
OK Then...

Let´s try this:

## in project pom.xml

```
   <repository>
      <id>nexus</id>
     <name>Sonatype Public Repo</name>
      <url>https://maven-us.nuxeo.org/nexus/content/groups/public</url>
   </repository>
```

and remove setting.xml from ~/.m2  
(from now we doesn´t not need it !)

Cheers

**Comment by paulsaurels** [comment]
Honestly, I don' t know if we can rely in the repository (https://maven-us.nuxeo.org/nexus),
 but now it 's the best solution we have...I guess!!! ;-) 

If in the future, we realise that we don't need any more those dependencies, we can remove them from project.

Cheers
